version: '3.9'

services:
    nginx:
        image: nginx:1.24
#        command: ["nginx", "-g", "daemon off;"]
        ports:
            - "8081:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static/:/usr/share/nginx/html
#        restart: always
#        stop_grace_period: 0s
    robear:
        ports:
          - "3000:3000"
        image: hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1
        working_dir: /app
        command:
            - sbt
            - run
#        build: .
#        restart: always
#        stop_grace_period: 0s
        volumes:
            - ./server:/app/
